---
dci_topic: OCP-4.9
dci_name: Test TNF v4.0.1 Using DCI
dci_configuration: Test TNF Certs Using DCI inside a container
do_cnf_cert: true
dci_openshift_app_image: quay.io/testnetworkfunction/cnf-test-partner:latest
tnf_suites: >-
  access-control
  networking
  observability
  platform-alteration
tnf_postrun_delete_resources: false
dci_openshift_app_ns: dci-tnf-test
dci_teardown_on_success: false
tnf_log_level: trace
dci_disconnected: false
tnf_config:
  - namespace: dci-tnf-test
    targetpodlabels:
      - app=dci-tnf-test
    operators_regexp:
    exclude_connectivity_regexp:
test_network_function_version: v4.0.1	
