dci_topic: OCP-4.9
dci_name: TestPreflight Operator Bundle Image Using DCI
dci_configuration: Run Preflight Operator Bundle Image from DCI
partner_creds: "/var/lib/dci-openshift-app-agent/auth.json"
do_preflight_tests: true
#preflight_test_certified_image: true
preflight_operators_to_certify:
  - bundle_image: "quay.io/opdev/simple-demo-operator-bundle:v0.0.6"
    index_image: "quay.io/opdev/simple-demo-operator-catalog:v0.0.6"
    # https://connect.redhat.com/projects/628b8f2819e6793741575daa/overview
    #pyxis_container_identifier: "628b8f2819e6793741575daa"

# To generate it: connect.redhat.com -> Product certification -> Container API Keys -> Generate new key
#pyxis_apikey_path: "/var/lib/dci-openshift-app-agent/pyxis-apikey.txt"
