apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .Values.dcinetipvlan.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
     #"helm.sh/hook": pre-install
     #"helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": {{ .Values.hook_delete_policy }}
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": {{ .Values.dcinetipvlan.name | quote }},
    "type": "ipvlan",
    "master": {{ .Values.dcinetipvlan.hostDevice | quote }},
    "ipam": {
      "type": "host-local",
      "subnet": {{ .Values.dcinetipvlan.cidr | quote }},
      "rangeStart": {{ .Values.dcinetipvlan.allocationPoolStartIp | quote }},
      "rangeEnd": {{ .Values.dcinetipvlan.allocationPoolEndIp | quote }},
      {{- if .Values.dcinetipvlan.routes }}
      {{- include "network_routes" .Values.dcinetipvlan.routes | indent 6 }}
      {{- end }}
    }
  }'
